#!/bin/sh
#
# Sample init script version 2
# Created by Rahul Panwar
#
# description: Run helloapp application as Linux service.
# chkconfig: 2345 80 20

# start function will be executed on startup
. /etc/init.d/functions

myname=`basename $0`
helloapp=/usr/local/bin/sayhello
RETVAL=0

# start function will be executed on startup
start() {
 echo -n "Starting $myname: "
 # start application command
 daemon $helloapp
 RETVAL=$?
 [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$myname
 echo
 return $RETVAL
}

# stop function will be executed on shutdown
stop() {
 echo -n "Stopping $myname: "
 # stop application command
 killproc $helloapp
 RETVAL=$?
 [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$myname
 echo
 return $RETVAL
}

# restart function will be executed for restarting the application
restart() {
 stop
 start
}

case "$1" in
 start)
  start
 ;;
 stop)
  stop
 ;;
 restart)
  restart
 ;;
 status)
  status $helloapp
 ;;
 *)
  echo "Usage: $myname {start|stop|status|restart}"
  exit 1
 ;;
esac
exit $?
